### ISSUE TITLE
deserialize issue

### ISSUE THREAD

**Issue by kavaro** [mobxjs/serializr#10]
Hi,

  Started using serializr recently (thanks for making this available) and am having trouble that 'Illegal state' error is thrown while deserializing. Have been able to reduce the problem back to the following small example. Not sure this is a bug or a config error on my side. Thanks for any help you can give ...

```
'use strict';

import {
    object,
    child,
    identifier,
    serialize,
    update,
    createSimpleSchema,
    deserialize,
    serializable,
    primitive,
    list
} from 'serializr';

class Route {
    @serializable(identifier()) id = '';
    @serializable(primitive()) pattern = '';

    constructor(id = '', pattern = '') {
        this.id = id;
        this.pattern = pattern;
    }
}

class Router {
    @serializable(list(object(Route))) routes = [];

    constructor(routes = []) {
        this.routes = routes;
    }
}

class Store {
    @serializable(object(Router)) router = new Router();

    addRoute() {
        this.router.routes.push(new Route('home', '/'));
    }
}

const store = new Store();
store.addRoute(); // WHEN THIS LINE IS REMOVED THEN THERE IS NO ERROR THROWN
const serial = serialize(store);
console.log(JSON.stringify(serial));
try {
    console.log('SUCCESS', deserialize(Store, serial));
} catch (err) {
    console.log('ERROR', err);
}
```
  

  Environment: node v5.10.0
  Babel: 
    presets: [ 'react', 'es2015', 'stage-0' ]
    plugins: [ 'transform-decorators-legacy', 'add-module-exports', 'jsx-control-statements' ]

**Comment by mweststrate** [comment]
This is a bug in serializr indeed. 1.1.5 should fix this. Thanks for reporting!

**Comment by kavaro** [comment]
Thanks for the ultra quick response. 1.1.5 indeed fixes the issue.
