### ISSUE TITLE
Backticks not being transpiled in compiled file. Causes issues in IE11.

### ISSUE THREAD

**Issue by rafaeldsousa** [mobxjs/serializr#106]
1.5.3 - Doesn't Work https://github.com/mobxjs/serializr/blob/f44cbd75618cef2f7361986580979b98ef5f7df2/src/core/serialize.js#L39
1.5.2 - Woks https://github.com/mobxjs/serializr/blob/c9ac7629508ce4b96af9582fb8168666c9635dd8/src/core/serialize.js#L49

![Screen Shot 2019-10-30 at 2 05 22 PM](https://user-images.githubusercontent.com/39249777/67821505-23d2fb00-fb22-11e9-95aa-3460ddbdf8d0.png)
![Screen Shot 2019-10-30 at 2 30 54 PM](https://user-images.githubusercontent.com/39249777/67821521-35b49e00-fb22-11e9-8dec-5fddd658ff55.png)

**Comment by mweststrate** [comment]
I think a this package is not tranpspiled at all ATM, (only rolled up to remove the ESM imports), so the simplest solution here is probably to replace the template literal with a normal string. PR welcome
