### ISSUE TITLE
Code is published but not transpiled to ES5

### ISSUE THREAD

**Issue by danfma** [mobxjs/serializr#114]
Yesterday, I sent a PR regarding IE problems with templated strings, but then I realized that the published code is not ES5 compliant, and that is the cause of the problems. It contains templated strings, destructuring, and spreads everywhere, and IE does not support that.

So, we have two options:

1) Transpile the published source code to ES5 (the safest one);
2) Put a note in the documentation, showing how to configure Webpack (for example) with an alias and then force it to be compiled with the generated bundle.

If allowed, I would like to set up the Typescript compiler to do the transpilation before publishing the package. Or, we can convert the whole code to Typescript as well! :P

What do you think, guys?

**Comment by mweststrate** [comment]
I think we should transpile indeed to prevent this from happening again.
Either rollup / babel / microbundle / TS is all fine I'd say :)

**Comment by pyrogenic** [comment]
I think we'd probably want to do the lightest-weight version — just babeling the source into ES5 — to keep the final code as lightweight as possible.

I do think moving to TypeScript would be great for maintainability in the long term. However, `serializr` supports things that cannot be expressed in TypeScript — for example, objects that have index signatures (`serializeAll()`) and explicit properties (`serializable()`) that aren't of the same type. To actually write the internals in a way that takes advantage of type safety would be a challenge.

While you can add this test in Javascript:

```js

test("[babel] @serializeAll", t => {
    @serializeAll
    class Store {
        a = 3

        @serializable(list(primitive()))
        explicit = []
    }

    const store = new Store
    store.c = 5
    store.explicit.push("example")

    t.deepEqual(serialize(store), { a: 3, c: 5, explicit: ["example"]})

    const store2 = deserialize(Store, { a: 2, b: 3, c: 4, explicit: ["other value"]})
    t.equal(store2.a, 2)
    t.equal(store2.b, 3)
    t.equal(store2.c, 4)
    t.deepEqual(store2.explicit, ["other value"])

    t.end()
})
```

Attempting something similar in TypeScript results in a compile error, "Property 'explicit' of type 'string[]' is not assignable to string index type 'number'.ts(2411)":
```
test("[ts] @serializeAll", t => {
    @serializeAll
    class Store {
        [key: string]: number;
        a = 3

        @serializable(list(primitive()))
        explicit: string[] = []
    }

    const store = new Store();
    store.c = 5;
    store.explicit.push("example")

    t.deepEqual(serialize(store), { a: 3, c: 5, explicit: ["example"] })

    const store2 = deserialize(Store, { a: 2, b: 3, c: 4, explicit: ["other value"] })
    t.equal(store2.a, 2)
    t.equal(store2.b, 3)
    t.equal(store2.c, 4)
    t.deepEqual(store2.explicit, ["other value"])

    t.end()
})
```

**Comment by andreaslarssen** [comment]
Holy moly this caused me (and my client) much pain. Somewhere between version 1.3 and 1.5 something, es6 syntax is introduced. Never struck me that this kind of change would be introduced between minor versions. Isn't this considered a breaking change?

**Comment by mweststrate** [comment]
No, it is a bug, and a was fixed in 2.0, in which the new build setup will now catch this in the future

**Comment by andreaslarssen** [comment]
What GH tag is NPM version 2.0? Is it just not tagged yet?

**Comment by mweststrate** [comment]
Doesn't seem to have a git tag indeed, but latest on npm is 2.0.3
