### ISSUE TITLE
How should circular dependencies be handled?

### ISSUE THREAD

**Issue by ecen** [mobxjs/serializr#129]
I have the following graph structure, which works fine.
```ts
class Node {
    @serializable(identifier())
    id: string = uuidv4()

    @serializable(list(reference(Node)))
    edges: Node[]
}

class Graph {
    @serializable(list(object(Node)))
    nodes: Node[]
}
```

Now I want to store additional information for each edge, so I create an Edge class and move the Node reference into this class, along with the new information:
```ts
class Node {
    @serializable(identifier())
    id: string = uuidv4()

    @serializable(list(object(Edge)))
    edges: Edge[]
}

class Edge {
    @serializable(reference(Node))
    n: Node

    @serializable
    weight: number
}

class Graph {
    @serializable(list(object(Node)))
    nodes: Node[]
}
```

**This does not work** and gives a `No modelSchema provided` error when each class is in its own module. (Or a `Class 'Edge' used before it's declaration` error on the Edge[] annotation when all classes are in the same file.)

I assume this happens because I have introduced a circular dependency between Node and Edge, but since Node can self reference using the reference annotation, I would think it possible to serialize this graph too, as long as the modelSchemas can be loaded. I have looked at #82 and #91, including the article describing the [internal module pattern](https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de) but have so far not had any success.

There are some workarounds I could use, like storing only the node ID in each Edge, or have the Graph take care of all Edge references, but that would require other parts of my code to run lookups to find a Node's associated Edges or vice versa.

**Is there a way to allow Node and Edge to have direct access to each other**, and what would that be?

**Comment by NaridaL** [comment]
serializr currently doesn't offer a forward ref mechanism, but you should be able to hack one in like so:

```ts
  @serializable(
      custom(
        (s: Node) => s.id,
        (jsonValue, context, _oldValue, done) => {
// this is basically what reference() does
          context.rootContext.await(getDefaultModelSchema(Node)!, jsonValue, done)
        },
      ),
```

**Comment by ecen** [comment]
Alright. Perhaps a built-in solution would be useful to have?

In any case, this solves my problem brilliantly. Many thanks!

**Comment by NaridaL** [comment]
@ecen Yeah, it would probably make sense. Note that I missed a bug in my previous comment, I've amended it. (context counts references so it returns an error instead of doing nothing if there are unresolved references, but if you don't call createCallback, you can get errors in some cases)

**Comment by ecen** [comment]
@NaridaL Hm... alright. The amended version gives a type error since createCallback takes an argument of type `(value: T) => void`, but done is of type `(err?: any, value?: any) => void`.

**Comment by NaridaL** [comment]
Yeah the createCallback return value handles errors itself. You need to do
value => done(undefined, value). Sorry about that.

**Comment by ecen** [comment]
Ah, thank you!

For future reference, I am now using
```ts
custom(
    (s: Node) => s.id,
    (jsonValue, context, _oldValue, done) => {
        // this is basically what reference() does
        context.rootContext.await(
            getDefaultModelSchema(Node)!,
            jsonValue,
            context.rootContext.createCallback(value => done(undefined, value)),
        )
    },
)
```
which solved my problem.
