### ISSUE TITLE
Decorator Example doesn't work via Babel 6x

### ISSUE THREAD

**Issue by KaySackey** [mobxjs/serializr#13]
In Babel 6, code that execute within the class body do not receive an instance of the class constructor if referenced. 

```
class Message {
    @serializable(list(object(Message)))
    comments = [];
}
```

The above code will simply result in an error  because at point of call Message will resolve to undefined.

Here's the error:

> Error: [serializr] No modelschema provided. If you are importing it from another file be aware of circular dependencies.

In Babel 5x it'll work because it creates the class constructor inline before the decorators parameters are resolved, and maintains it as its original name (e.g. Message), instead of the mangled format for the rest of the Babel compiler's transforms to use.

TypeScript does the same thing, and thus it works fine.

**Comment by mweststrate** [comment]
Yeah these kind of circular references are tricky in javascript :(. The way around currently is to define the propSchema after declaring the class, e.g.

`getDefaultModelSchema(Message).props["comments"] = list(object(Message))` (from the top of my head)

**Comment by KaySackey** [comment]
Does serializable have to be a decorator? If we can make a call like comments = serializable(list(object(Message)) then it'll execute correctly since it's added to the class constructor in Babel 6.

I know that observable works that way in MobX.

**Comment by mweststrate** [comment]
Mmm not sure, how is that different from what I did in my previous message?
