### ISSUE TITLE
Context args is private in new release 2.0

### ISSUE THREAD

**Issue by Dar0n** [mobxjs/serializr#135]
Hello,
we were using your powerful library for quite some time.

Today I've decided to upgrade to a newer version 2.0.3 which was a major upgrade, and have faced some of the breaking changes. One of them is that args field is now private on context object during custom deserialization. 

Is there a workaround? How are we supposed to pass args now?
Thank you!

**Comment by NaridaL** [comment]
Yeah, this seems like a bug...
