### ISSUE TITLE
Async custom deserialization: is the function type definition correct?

### ISSUE THREAD

**Issue by Dar0n** [mobxjs/serializr#136]
Hello,

Another request from my side after update to 2.0.3. Sorry for spamming you. I apologize if my request is due to lack of understanding.
I am using custom deserialization in a _typescript_ project with async deserialize function.After today's upgrade I am getting an error message:
"Promise returned in function argument where a void return was expected.".

Async function signature is (value, context, oldValue, callback) => void, according to documentation and type definitions. But shouldn't it be (value, context, oldValue, callback) => Promise\<void\> for an async function?

Is there other way to process async request inside **deserialize** function without making **deserialize** function  _async_?

Thank you!

**Comment by NaridaL** [comment]
Maybe changing the signature to `=> void | Promise<void>` would be sensible yeah...

In any case you can use the current version by not making deserialize async and doing something like:

```
 (value, context, oldValue, callback) =>{
myPromise.then(result => callback(undefined, result))
}
```

**Comment by mweststrate** [comment]
It might be that the returned promise is chained upon, which would break
with the above? Probably `any` casting the returned promise is safer is it
doesn't change the runtime semantics

**Comment by Dar0n** [comment]
@NaridaL @mweststrate 
Thank you for a fast reply! I think I actually managed to rewrite the **deserialize** function according to Adrian's suggestion and it seems to work(fingers crossed).

However, in general we try to use async/await syntax in our codebase.
@mweststrate I used await inside **deserialize** function, hence I had to declare the whole function as async. Hence the error message. Do you reckon, I could also leave it async and add some typescript casting?

**Comment by mweststrate** [comment]
I'm not to familiar with that code anymore, but I probably the acceptable
return types should be updated as suggested above, making it possible to
use async functions.

**Comment by NaridaL** [comment]
OK, after some more thought, changing the signature as I suggested above seems like the wrong choice. It strongly suggests that serializr will do something with the promise, which it doesn't.

As far as I can see, the "Promise returned in function argument where a void return was expected." isn't a TypeScript error, but from eslint ( https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md ). TypeScript will (rightly) allow you to assign a function which returns anything to something typed as returning void.

The right choice here seems to be to disable that warning (in general or for that line) or to rewrite the function.

(You can do `() => (async () => { ... })()` if you want to use async, although I'm not entirely sure I'd recommend it...)

**Comment by mweststrate** [comment]
@NaridaL, agreed. I had in my memory the vague idea that you _could_ return a promise there, and if you did, that it would make the entire process async. If that isn't the case it should stay `async` indeed. If it is es-lint complaining, not TS, I wouldn't further bother about it. It can be suppressed by a simple ignore line, and there is really no way in general to make eslint happy for everybody everywhere with all the pedantic rules it can have.
