### ISSUE TITLE
ModelSchema-based custom (de)serialization

### ISSUE THREAD

**Issue by jaredru** [mobxjs/serializr#14]
The `custom` `PropSchema` is nice, but it feels like there should be a way to do custom serializers on the `ModelSchema` itself.  For instance:

``` javascript
function serializer(foo) {
    // returns a serialized, primitive representation of foo
}

function deserializer(raw) {
    // returns an instance of Foo
}

@serializable(serializer, deserializer)
class Foo {
    ...
}
```

The syntax above isn't particularly important, but rather the notion that, externally, other objects can continue to `serialize(foo)`, `deserialize(Foo, json)`, and decorate `@serializable(object(Foo)) foo` without regard for Foo's internal (de)serialization mechanism.

**Comment by mweststrate** [comment]
Closing for the  lack of further interest
