### ISSUE TITLE
How to serialize JsonNode?

### ISSUE THREAD

**Issue by ScoobyMax** [mobxjs/serializr#153]
on the server side:
```
JsonNode rootNode = JSON_MAPPER.readValue(resultDocs, JsonNode.class);
orderDTO.setResultDocumentsObj(rootNode);
```

at the REST we got:
![image](https://user-images.githubusercontent.com/21054140/126776999-af1bc42b-ec3d-483f-b362-491dbcc413cd.png)

on client side i have that classes with:

```
export class Conversation {
...
  @serializable(object(ResultDocumentsObj))
  resultDocumentsObj: ResultDocumentsObj;
}
```

```
export class ResultDocumentsObj {
...
  @serializable(alias('resultDocumentsPanel', list(object(ResultDocumentsPanel))))
  resultDocumentsPanel: ResultDocumentsPanel[];
}
```

```
export class ResultDocumentsPanel {

  @serializable
  resultDocName: string;
...
}
```

BUT it can't serialize resultDocumentsPanel from JsonNode

**Comment by mweststrate** [comment]
That looks like pretty strange JSON you got there. Normally that should read something like `"resultDocumentsPanel": [{ resultDocName: "dsfgh", "resultDocument": "xxx.png" }]` etc. I'd talk to the owner of your REST endpoint, this doesn't represent an array in json, but just a plain object with funny key names.
