### ISSUE TITLE
how to serialize/deserialize ES6 Set

### ISSUE THREAD

**Issue by jianyunli** [mobxjs/serializr#157]
I tried to use `list(primitive())`, it gives me an error

**Comment by jianyunli** [comment]
ok, I figured out the serialize part using custom function

` set: custom(m => {
        const result = [];
        m.forEach(value => result.push(value));
        return result;
    }, () => SKIP)`

for the deserialize part, anyone could help me? how could I new a Set? the factory method is on the ModelSchema, not on the PropSchema, right?

**Comment by NaridaL** [comment]
You can just do 

```
custom(
  m => Array.from(m),
  jsonArray => new Set(jsonArray))
```

**Comment by jianyunli** [comment]
Thank you for this elegant solution, much better than mine

> You can just do
> 
> ```
> custom(
>   m => Array.from(m),
>   jsonArray => new Set(jsonArray))
> ```
