### ISSUE TITLE
expected modelSchema, got undefined error

### ISSUE THREAD

**Issue by jianyunli** [mobxjs/serializr#158]
I have a three layer relationship

Class Simulation -> Class Network -> Links

Simulation instance contains a Network instance, which contains a Map<id, Link>

I called `createModelSchema` on each class constructor, everything works fine for `serialize` part, but I got the error for the 'deserialize'

can anyone point what did I do wrong?

```
class Network {
    constructor() {
        this.Links = new Map(); 
        createModelSchema(Network, {
            Links: mapAsArray(object(Link), "id"),        
        })
    }
}
```

```
class Link {    
    constructor(id, a_points) {
        this.id = id;
        this.points = a_points; 
        createModelSchema(Link, {
            id: identifier(),
            points: alias('p', list(list(primitive()))),
        })
    }
}
```

**Comment by NaridaL** [comment]
As far as I can see from the examples, you shouldn't be calling createModelSchema from the constructor but rather after the class definition.

**Comment by jianyunli** [comment]
Works like charm, thanks again Adrian! Happy New Year!
