### ISSUE TITLE
how do I keep the map key as number

### ISSUE THREAD

**Issue by jianyunli** [mobxjs/serializr#161]
I used map() for my ES6 Map myField, looks like it converted key to strings, how can I keep it as the number?

`createModelSchema(MyClass, {   
    myField: map()
})`

**Comment by OniOniOn-** [comment]
I extended custom with list to support dictionary primitive key/any PropSchema values.
Map<K, V> =serializer=> [K, V][] =deserializer=> Map<K, V>

**Comment by jianyunli** [comment]
thanks, does it work?

**Comment by NaridaL** [comment]
Was the actual key being converted to string, or were the types wrong?

**Comment by Lechros** [comment]
It is converted to JS object, which only supports string key.
