### ISSUE TITLE
update() does not deep merge?

### ISSUE THREAD

**Issue by ConneXNL** [mobxjs/serializr#18]
Is it correct that update() does not deep merge / do anything recursive and is only capable of doing a shallowMerge?

What is a good practice to replace / merge an entire tree of mobx state objects or modify bits and pieces inside the tree?

**Comment by mweststrate** [comment]
update should be deep merging (provided that the relations are compositional and not references)

**Comment by ConneXNL** [comment]
Prepared the following gist to show my problem:

https://gist.github.com/ConneXNL/63fe5d1788c08fc56b8a2ae364898a5f

**Comment by mweststrate** [comment]
ah yes that is deliberately, otherwise deep deletions could not be
expressed in the json. Maybe there should be a separate `merge` operation
then

Op do 6 okt. 2016 om 10:45 schreef ConneXNL <notifications@github.com>:

**Comment by ConneXNL** [comment]
In my code base in most / all cases I want to merge instead of replace for maps whereas I want to replace with arrays. However I guess this depends on the use-case whether you would want to replace or merge. 

Making a top merge function in serializr wouldn't make much sense as within the tree you might want to switch strategy. Binding the strategy on the modelSchema could work but wouldn't be very flexible.

Maybe a callback on the update that will be called for each node to return a strategy. By default this could remain the current "replace" implementation. But if specified one could do a type check and return a strategy for a specific node.

It could look something like this:

```
import { update, merge, replace} from "serializr";
update(building, updatedJson, (object,  key, depth) => {
   if (object instanceof Building && key === "levels"){
        return merge;
   }
);
```

**Comment by mweststrate** [comment]
hmm sounds quite complicated. Why is your json complete at some points while extending at other points? is it because of how you invoke your api's .Is the extending maybe only at a single specific piont, `levels` in this case?

**Comment by ConneXNL** [comment]
I want to keep the network packets as small as possible thus I don't send over the whole tree but just the parts that I want to update in the existing tree.

For my use case, when I use maps something is an actual entity, in this case I don't want to replace the entities but merge its properties or add a new entity to the map (for example when I want to add a level as in the git example).

But let's say the level would have a string array of furniture (f.e. furniture : ["Bed", "Pool table"]. This whole furniture might change with an update to for example just ["Bed"]. In this case I want to replace the existing array instead of merging it (this also gives me the flexibility of being able to remove something from the array).

**Comment by mweststrate** [comment]
Where you able to express this using a custom serializer? I think that should be the most elegant approach and quite similar to your above example

**Comment by mweststrate** [comment]
Closed for inactivity. Feel free to re-open
