### ISSUE TITLE
Support for a "postprocess" operation

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [mobxjs/serializr#20]
Hello,

I know about factory (that is run before deserializing the props). But sometimes I want to do something more than deserializing props. Something i would usually do in the constructor but since I need the props to be defined before I can run this. I basically have to do the deserialization myself in the factory reading the json from the context, and sadly that defeats the purpose of serializr.

Did I missed something or this is something that could be added ? 

Thanks

**Comment by GuillaumeLeclerc** [comment]
My solution right now is to have two schema. My real schema. and another that only contain a factory that deserialize using the first schema do the operation and return. It works but it seems a little bit hacky. Especially that factories can't be asynchronous, it fails if the second schema is asynchronous.

**Comment by mweststrate** [comment]
Could you share an example of the problem and your solution?

**Comment by mweststrate** [comment]
Closed for inactivity. Feel free to re-open

**Comment by GuillaumeLeclerc** [comment]
Sorry I missed your previous message.

My use case is very simple. I have a class that needs to subscribe to Rx streams, but the stream to listen to depends on the attributes that are deserialized. So I can't do it in the factory. My solution is to add another function (It's working in my fork for now) so the process becomes:

- call factory
- deseriailze data
- call postProcess
