### ISSUE TITLE
Typo in the exports

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [mobxjs/serializr#21]
**https://github.com/mobxjs/serializr/blob/master/serializr.js#L1078** Is it normal ?

**Comment by mweststrate** [comment]
Oops... No it isn't! Thanks for spotting

Op vr 7 okt. 2016 om 22:19 schreef Guillaume Leclerc <
notifications@github.com>:

**Comment by mweststrate** [comment]
Fixed in 1.1.8
