### ISSUE TITLE
Conditional @serializable

### ISSUE THREAD

**Issue by fusepilot** [mobxjs/serializr#26]
In my application I'm using serializr for both offline persistence and undo/redo on my mobx stores. When saving and reloading the stores for offline I need all ````@serializable````'s to be serialized, as it works currently. But when undo/redoing I only need a subset of the ````@serializable````'s to be serialized.

Maybe something like this could be added:
````
class Time {
  @serializable @observable startNanoseconds: number = 0
  @serializable @observable endNanoseconds: number = 5 * 1e9
  @serializableIf(() => global.serizalizeForOffline) @observable currentNanoseconds: number = 0
}
````

So ````serializableIf```` would only be serialized/deserialized/updated if ````global.serizalizeForOffline```` is true.

**Comment by mweststrate** [comment]
Isn't the `@serializable(serializer, deserializer)` to achieve this? Or would that be too much boilerplate? It doesn't feel very generic so far (and relying on global flags might not always be that scalable).

**Comment by fusepilot** [comment]
I didn't realize you could provide a serializer and deserializer directly to ````serializable```` when I filled the issue. I thought I needed to use ````custom```` or something. Anyways, I haven't been able to get the behavior I need using it yet, but I think it might be because another issue. I'll close this and open a new one once I've narrowed it down further. Thanks.
