### ISSUE TITLE
[Feature Request] Deserialize, serialize lists of class instances

### ISSUE THREAD

**Issue by Podlas29** [mobxjs/serializr#28]
Hi.
Let me just warn you that I am new to serializr. If there is already functionality I look for, feel free to close this issue. ;)

I want to serialize list of my custom classes, in order to save them to local storage. I do not want to wrap them in another class, since for my purposes it would just be boilerplate, without much value.

After reading readme, I was under the impression, that following code would work:

```javascript
deserialize(list(MyClassConstructor)), json)
```
but seems I was wrong

Is there a better way to achieve what I want, or (if it is currently impossible) would you be open to idea of extending library for such purposes (I would gladly tinker in the code myself)?

Thanks in advance and have a great day

**Comment by agilgur5** [comment]
You don't need `list` (that's also only meant for `PropSchemas`), `deserialize(MyClassContructor, json)` will work fine as it auto detects if it's an array or single object.

**Comment by Podlas29** [comment]
Well then there was issue with typescript typings which would not let me do such thing. I made pr: https://github.com/mobxjs/serializr/pull/29

**Comment by mweststrate** [comment]
Closing this issue, see also the PR. Use case seems to be too advanced for serializr itself (there are many possible patterns). Either a custom deserializer or somethling like mobx-state-tree is recommended here :)
