### ISSUE TITLE
Recipe number 5 doesn't work

### ISSUE THREAD

**Issue by rafales** [mobxjs/serializr#31]
Recipe "use custom factory methods to reuse model object instances" doesn't work as factory does not receive second argument. I'm working on reference-counted identity cache and this would be a VERY useful feature.

It looks like the argument should be passed here: https://github.com/mobxjs/serializr/blob/master/serializr.js#L460

**Comment by rafales** [comment]
Ok. This is actually a bug in the docs - you can access json data with `context.json`.

**Comment by mweststrate** [comment]
@rafales would you mind creating a PR to update the docs?
