### ISSUE TITLE
Polymorphism and deserialization

### ISSUE THREAD

**Issue by fabsantini** [mobxjs/serializr#33]
Hi,

I have this small example: B and C are classes that extend the base class A. The serialization portion works just fine. However, once I retrieve the serialized object "o" later on, I have no idea what model schema to use for the deserialization portion (it could be B or C). Can I deserialize polymorphic classes?

Please, consider that I am new to serializr!
 
```
class A {
    @serializable public a: string;

    constructor(aV: string) {
        this.a = aV;
    }
}

class B extends A {
    @serializable public b: string;

    constructor(aV: string, bV: string) {

        super(aV);
        this.b = bV;
    }
}

class C extends A {
    @serializable public c: string;
    @serializable public cn: number;

    constructor(aV: string, cV: string, cnV: number) {

        super(aV);
        this.c = cV;
        this.cn = cnV;
    }
}

describe('test', () => {

    it('test', () => {

        let bb: B = new B("vaB", "vb");
        let cc: C = new C("vaC", "vc", 1);
        let o: any = serialize(cc);

        console.log(o);
        console.log(deserialize(B, o)); // <--- What should I use for model schema?
    });
});
```

**Comment by mweststrate** [comment]
See also #30, this seems to solve your case nicely? cc @JordinKee

**Comment by JordinKee** [comment]
Yes, this is the same situation I tried to solve with that PR.

**Comment by mweststrate** [comment]
Polymorphism is a too complex case to handle generically within serializr. Either use custom (de)serialization or mobx-state-tree for this.
