### ISSUE TITLE
update() doesn't use getDefaultModelSchema

### ISSUE THREAD

**Issue by jbrantly** [mobxjs/serializr#36]
My understanding is that `update` should have roughly the same semantics as `deserialize`. However, `deserialize` calls `getDefaultModelSchema` for a passed in modelSchema, but `update` does not. This causes something like the following to fail:

```
update(MyClass, myInstance, myJson)
// => error "update failed to determine schema"
```

**Comment by mweststrate** [comment]
Correct, fixed in `1.1.10`. Thanks for reporting
