### ISSUE TITLE
Adding formatting to date()

### ISSUE THREAD

**Issue by superplussed** [mobxjs/serializr#37]
@mweststrate is there a specific date formatting library you would use for this?  I'm guessing moment.js is too big, but I don't know what a good alternative is.

```
function date(format) {
    return {
        serializer: function(value) {
            if (value === null || value === undefined)
                return value
            invariant(value instanceof Date, "Expected Date object")
            if (format) {
                return moment(value.getTime()).format(format);
            }
            return value.getTime()
        },
    }
}
```

**Comment by RainerAtSpirit** [comment]
@superplussed Have you looked at https://github.com/taylorhakes/fecha?

**Comment by mweststrate** [comment]
Personally, for simplicity sake, I tend to use epochs as date format. But your backend has to support that of course.

**Comment by superplussed** [comment]
@RainerAtSpirit that's a great package!  @mweststrate would you consider a PR that used fecha in the format I outline above?  I assumed you were looking for something like this because of the TODO: add format option? comment I saw in the date function.

**Comment by superplussed** [comment]
The one downside I see as I proposed above is that it's weird to do this:

```
@observable @serializable(date('YY-MM')) createdAt;
```

Since the model is constraining the view component's ability to format the date as it pleases.  The other idea I had which follows more closely with how my own project uses decorators, is that each date field is instantiated as a decorator class, so that you could imagine having: 

```
@observable @serializable(dateDecorator()) createdAt;
```

And the dateDecorator is a class that gives several utility functions such as: 

```
createdAt.date // returns javascript date 
createdAt.format('YYYY-MM') // allows the view components to still have control over formatting
createdAt.timeAgo() // 3 days ago
```

**Comment by superplussed** [comment]
And actually this is probably outside the scope of what date() should do, as I can just wrap the date in a decorator with custom.  But the first option seems to fulfill the comment in the code no?

**Comment by mweststrate** [comment]
@superplussed I think that the format should only represent how the data should be serialized, but client side it should always be  a `Date` object, so given that it doesn not limit users? I'll happily accept a PR that adds that. Fecha seems nice as it is a small dep.

**Comment by brikou** [comment]
@superplussed https://github.com/date-fns/date-fns is really good

**Comment by mweststrate** [comment]
closing issue, `custom` types are perfectly fine for this imho, to built such an abstraction on top of it in user land code
