### ISSUE TITLE
Can createModelSchema stop calling class constructor?

### ISSUE THREAD

**Issue by yamsellem** [mobxjs/serializr#55]
It seems very strange to me that `createModelSchema` associated with a class call its constructor first thing. This can creates weird situation where the constructor validate some. Is there a way to change that?

```javascript
const test = require('ava');
const { createModelSchema, primitive, serialize, deserialize } = require('serializr');

class Todo {
    constructor(body) {
        console.log(body); // logs {} and then { name: 'things' }
    }
}

createModelSchema(Todo, {
    name: primitive()
});

test.only('deserialize', t => {
    const todo = new Todo({ name: 'things' });
    t.is(todo.name, 'things');
});
```

Thanks.

**Comment by alexggordon** [comment]
The reason for this, I believe, is `createModelSchema` has to have all the information to instantiate an instance of the class. There are some other arguments like `factory` for `createModelSchema` that let you tell it how to create the class, but if any portion of the class creation fails when calling `createModelSchema`, then it will most likely fail upon deserialization. If you'd like to customize how the class is instantiated, you can pass in the `factory` argument to change it.

**Comment by yamsellem** [comment]
Thanks for your answer.

May a noop could be used for this callback if none is provided?

This way, it would be a better developer experience, and the doc would be
alright. Right now the doc clearly stated that only two arguments is enough
(I've done some digging in the source to understand that a noop is needed
there).

Thanks again.

**Comment by alexggordon** [comment]
I'm not sure I understand? A `noop` is needed where? You don't need to have a constructor if you don't have any logic that goes in it.

**Comment by yamsellem** [comment]
Hi @alexggordon, sorry for the confusion, I was talking about a noop for #54 in:

Instead of being force to write this:
`Object.assign(this, deserialize(Todo, body, () => {})); `

Use a noop in the library code to allow to write this:
`Object.assign(this, deserialize(Todo, body)); `

**Comment by alexggordon** [comment]
Using Object.assign kind of defeats the point of using `serializr` though. Serializr is designed to replace the initialization process. 

I made an [example on runkit](https://runkit.com/alexggordon/serializr-issue-55) to illustrate what I'm talking about. See how in the ```console.log(deserialize...``` I pass a class and javascript object to `deserialize`, and the result is an instance of the class, with the attribute name? But I never call `new Class()`? That's more how it's designed to be used. 

As far as the "serializables" field, the issue I have with that, is that ties the schema definition to the class. What if you want different fields based on some arbitrary value? 

```
if (foo) {
  createModelSchema(Todo ....)
} else if (bar) {
  createModelSchema(Todo ....)
}
```

That's more why the function exists, just for additional flexibility.

**Comment by alexggordon** [comment]
Closed for inactivity
