### ISSUE TITLE
Separate the file into multiple maintainable module parts ?

### ISSUE THREAD

**Issue by chengjianhua** [mobxjs/serializr#56]
@mweststrate @alexggordon @maxdeviant 

Maybe we can separate the "big" js file into multiple modules, It's easier to maintain portions of this project and make it more readable. It's nice to bundle this by `rollup`.

Any ideas ?

**Comment by maxdeviant** [comment]
@chengjianhua I'm all for splitting up the code. Having separate files also makes it easier in the future if we want to progressively migrate to TypeScript/Flow :smile:

**Comment by chengjianhua** [comment]
@maxdeviant How do you guys arrange the work ? So I just waiting to the accomplishment of splitting code what you are doing or whether there are something that I can do for it ?

**Comment by alexggordon** [comment]
Fine by me. I think the best strategy I can think of would be to (in different PR's)

1. Modify the `publish.js` script in the root repo to support rollup, (by just rolling up the single js file). Alternatively, we could also block this by switching first to something like np, as [was suggested](https://github.com/mobxjs/serializr/pull/52#issuecomment-320449819).

2. Once we've tested the new publish script, we can begin thinking about a logical separation of the file. Most likely, it will sit somewhere in the area of 

```
types/
  primitive.js
  identifier.js
  date.js
  alias.js
  list.js
  map.js
  etc...
api/
  createSimpleSchema.js
  createModelSchema.js
  setDefaultModelSchema.js
  getDefaultModelSchema.js
  etc...
utils/
  decorators.js (serializable)
  etc...
core/
  serializer.js
  deserializr.js
```

3. Once that's done, evaluate typescript, and any further actions that need to be done. Obviously, this is a back of the napkin plan, but I think this would work just fine, given that the file itself is pretty small. If you'd like to do the initial PR, I'd be happy to comment/review/contribute.

**Comment by chengjianhua** [comment]
Awesome, I'd like to do the initial PR, the weekend is the time to do something ~ 

FYI.

As for improving the the release of repo, how about considering the `CHANGELOG` generator [(standard-version)](https://github.com/conventional-changelog/standard-version).

I use it in internal projects, It can generate neat and detailed release notes for us.

**Comment by alexggordon** [comment]
Closing this as it's been merged.
