### ISSUE TITLE
getDefaultModelSchema by string Class name

### ISSUE THREAD

**Issue by ChristophAtAdlos** [mobxjs/serializr#59]
Is it possible to get the modelSchema by a string?

What I know:
class BoxModel {...}
getDefaultModelSchema(BoxModel);

What I want:
class BoxModel {...}
let model = "BoxModel";
getDefaultModelSchema(model);

Is there a way to do something like that?

**Comment by mweststrate** [comment]
That is tricky, 

1. you would need some global state to track that (which could fail if (accidentally or intentionally) serializr is used multiple times in your project)
2. Nobody will guarantee `BoxModel` is actually unique
3. `BoxModel`'s name will probably be minified away into `uAg` or something as useful if you use a minifier for your production build.

Note that you can just store the model schema's in an arbitrarily map yourself if you want access to them by string

**Comment by ChristophAtAdlos** [comment]
I'll use it in a single script. I think, this way, 1 and 2 are no problem.  

Is this what you mean:  
```
import { BoxModel } from "./BoxModel";
import { RawModel } from "./RawModel";
const map = new Map();
map.add("BoxModel", BoxModel);
map.add("RawModel", RawModel);

const model = "BoxModel";
getDefaultModelSchema(map.get(model));
```

**Comment by mweststrate** [comment]
Yes, but I can't introduce bugs to a lib because you maybe wouldn't
encounter them ;-)

Op di 5 sep. 2017 om 17:06 schreef ChristophAtAdlos <
notifications@github.com>:
