### ISSUE TITLE
Serialize * all props recursively

### ISSUE THREAD

**Issue by scisci** [mobxjs/serializr#72]
Hi, if I have a vanilla js object like:

```
var data = {
  foo: 'bar',
  fobject: {
    fprop: 'fval'
  }
};
```

And I serialize it using the '*' all-props schema. It won't recursively serialize. It only serializes primitive values. What if I want the entire deep object serialized as-is?

**Comment by scisci** [comment]
It seems I can do this:

```
serializr.custom(
  model => {
    return model;
  },
  obj => {
    return obj;
  }
)
```

Is this fine?

**Comment by mweststrate** [comment]
That is correct, if it is recursively serialize it means it is serialize in
itself and you shouldn't need to do anything
