### ISSUE TITLE
Serialization Groups

### ISSUE THREAD

**Issue by j** [mobxjs/serializr#79]
Is it possible to have different serialization groupings?

If I want to deserialize from a MongoDB document (regular object) to a User class and a plain "JSON" object (such as form input).

The form input id field would be a string that needs to be converted to a ObjectID, and the MongoDB document is already an ObjectID so it doesn't need the cast.

**Comment by alexggordon** [comment]
@j can you give an example of when you'd need this? I'm not quite sure I understand your use case

**Comment by andreaslarssen** [comment]
+1

**Comment by alexggordon** [comment]
Closed for inactivity.

**Comment by andreaslarssen** [comment]
Use case: 

1) User logs in, we deserialize user entity from API request. 
2) User changes info, and wants to update server, so we update the entity.
3) Not all entity attributes should be PUT, so we want to exclude password (example) before sending request.
