### ISSUE TITLE
Really struggling with circular dependencies

### ISSUE THREAD

**Issue by robclouth** [mobxjs/serializr#82]
Any tips? 
I tried putting all the createModelSchemas in a single file. Nope.
Tried using a mix of @serializable and createModelSchema after the class defs. Nope.
I'm pulling my hair out!
I didn't even know circular deps in javascript was an issue until I started using serializr...

**Comment by alexggordon** [comment]
Can you give an example of what code is causing you an issue?

**Comment by mweststrate** [comment]
Here is some general guide on how to deal with circular deps in javascript modules: https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de

**Comment by 1R053** [comment]
generally, you'll have to use references - see e.g. the related question in #91
