### ISSUE TITLE
Is there any way to use serializr with Knockout in theory?

### ISSUE THREAD

**Issue by cervengoc** [mobxjs/serializr#84]
Due to some really old legacy components we need to support IE6, so we must use `knockoutjs` instead of `mobx`.

Do you think it's possible to configure serializr to be able to work with a `knockoutjs` based viewmodel?

**Comment by alexggordon** [comment]
Can you expand on that? I'm not sure what exactly you mean in terms of configuring for a knockoutjs based viewmodel?

**Comment by cervengoc** [comment]
Hi @alexggordon, I thought something like configuring `serializr` to be able to get and update the viewmodel properties using the `knockoutjs` observable setter syntax instead of the standard property getters/setters.

**Comment by cervengoc** [comment]
Oh, I'm sorry. Sure, here is a simple case.

Using `update` with standard properties (like mobx):

```
target.a = source.a;
if (source.nested && !target.nested) {
  target.nested = new Nested();
}
target.nested.b = source.nested.b;
```

Using `update` with `knockout` observables:

```
target.a(source.a);
if (source.nested && !target.nested()) {
  target.nested(new Nested());
}
target.nested().b(source.nested.b);
```

Basically in `target` we have `knockout` observables, which are functions. If we call them with no arguments, that's the getter. If we call them with a single argument, that's the setter.

What I'd like to achieve is to make `serializr` use this kind of mechanism when ever setting property values. I hope this makes sense.

**Comment by alexggordon** [comment]
So I think part of the issue is that I'm not super familiar with KO. The biggest issue it seems will be mapping between serializable values and KO observables computed. 

http://jsfiddle.net/alexggordon/0dLu36jg/

I made a simple example. Notice how we have to define all the computed functions after the deserialization? 

Honestly, it might be more trouble than it's worth, but that's my personal opinion.

**Comment by cervengoc** [comment]
Usually the observables and computeds are defined at construction time, something like this (TypeScript syntax)

```ts
class Person {
  firstName = ko.observable("");
  lastName = ko.observable("");
  fullName = ko.pureComputed(() => this.firstName() + " " + this.lastName());

  someMethod() { ... }
}
```

So the model structure is ready after the constructor with some default data. So a manual deserializing would look something like this.

```ts
function deserializePerson(inputObject) {
  var model = new Person();

  model.firstName(inputObject.firstName);
  model.lastName(inputObject.lastName);

  return model;
}
```

So my point is that `serializr` should not create the observables, nor the computeds, just populate them during the object deserialization. Hope it makes sense.

**Comment by alexggordon** [comment]
Yup, I understand your point, but you have to integrate the ko.observable to serializr. Serializr does stupid updates to values--it doesn't know that you can't do `this.firstName = 'Alex'` and that you have to do `this.firstName('Alex')`. That's what I was pointing out with the JSfiddle, is if you're going to integrate the two, you'll have to create a set of bindings back and forth to get values into a KO viewmodel and to get them out of it

**Comment by cervengoc** [comment]
I understand, so basically currently we have no option to *teach* `serializr` how to update properties. 

Your fiddle will unfortunately not work in a real-life scenario as referential integrity of observables is a must to make the bindings work properly. In other word, you cannot assign a new observable to a property, but only update the existing.

Thank you very much for your investigation though.

**Comment by alexggordon** [comment]
Yeah, sorry, no easy solution. Good luck!
