### ISSUE TITLE
Serializing an string array

### ISSUE THREAD

**Issue by andreaslarssen** [mobxjs/serializr#89]
Hi.

Quick question:
Is raw() the way to go for serializing a TypeScript string array?

`
@serializable(raw()) stuff: string[];
`

**Comment by alexggordon** [comment]
By string array do you just mean an array of strings? If so, then you just need

```@serializable(list())```

that's technically short for 

```@serializable(list(primitive()))```

**Comment by alexggordon** [comment]
I'm not sure what you mean that it's not a primitive. Strings are primitive. 

Here's a [runkit example](https://runkit.com/alexggordon/strings). If that isn't what you're referring to can you modify/fork that example to explain?

**Comment by andreaslarssen** [comment]
So I see you wrap the primitive() in the list(). That's my weekend cue. Thanks.
