### ISSUE TITLE
Problems with models that have circular references 

### ISSUE THREAD

**Issue by robclouth** [mobxjs/serializr#9]
There doesn't seem to be any way I can set this up so that two classes that reference each other can be serialized, without causing either a 'undefined' error or 'No modelschema provided' error. Any tips?

**Comment by mweststrate** [comment]
yep this is a limitation in the language spec atm, and I don't know an universal solution for it (classes are not hoisted like functions). However by defining the model schema for one of your classes after declaring the class you can avoid this issue, see this test:

https://github.com/mobxjs/serializr/blob/ab89944606c26362edbb863741506a164adbd283/test/classes.js#L118

**Comment by robclouth** [comment]
Hmm, I think I'm just generally confused. Basically I have a list of 'shaders'. Each shader can be edited separately. I need each edit to be saved automatically, and also the list of shaders to be automatically saved if a new one is added or removed.

```
class ShaderStore {
    @observable shaders = [];

    constructor() {
        store.get('shaders')
            .then(shaders => {
                update(this, shaders);
            })

        reaction(
            () => this.shaders.map(shader => shader),
            () => {
            store.save('shaders', serialize(this))
                .then(() => store.get('shaders'))
                .then(shaders => {
                    console.log(shaders);
                })
        });
    }

    createShader() {
        var shader = new Shader(this);
        this.shaders.push(shader);
        return shader;
    }

    removeShader(shader) {
        this.shaders.splice(this.shaders.indexOf(shader), 1);
        shader.dispose();
    }
}

export class Shader {
    id = null;

    @observable title = '';
    @observable author = '';

    store = null;

    patch = null;

    constructor(store) {
        this.store = store;
        this.id = uuid.v4();

        this.patch = new Patch();

        reaction(
            () => ({
                title: this.title,
                author: this.author,
                patch: this.patch
            }),
            () => {
            store.save(this.id, serialize(this))
        });
    }

    delete() {
        this.store.removeShader(this);
    }
}

createModelSchema(ShaderStore, {
    shaders: list(reference(Shader))
});

createModelSchema(Shader, {
    id: identifier(),
    title: true,
    author: true, 
    store: reference(ShaderStore)
});

const instance = new ShaderStore();
export {instance as ShaderStore}
```

**Comment by mweststrate** [comment]
Some questions:
1. can you share the stacktrace
2. can you share the json docs you expect. Note that if you expect the shaders to be stored as part of the store, you should use `list(object(Shader))` instead of reference. If you don't want them to be part of the same json, make sure to provide a lookup function to reference to be able to deserialize again. See for example the [docs](https://github.com/mobxjs/serializr#reference)
3. If you can demonstrate the issue in a fork of this JSBin that would be great: http://jsbin.com/nakitu/edit?js,console

**Comment by robclouth** [comment]
Hey, thanks for the help. After digging around I've managed to make some progress but hitting a new problem deserializing an object that has a sub object. It errors with "Illegal State" on the assertion on line 493: invariant(this.isRoot).
'this.isRoot' is false and the error is thrown. The jsbin below shows this. What does this mean?

http://jsbin.com/xatajovasu/1/edit?js,console

**Comment by mweststrate** [comment]
can you upgrade to the latest version? I think that fixes this

Op za 13 aug. 2016 13:58 schreef robclouth <notifications@github.com>:

**Comment by robclouth** [comment]
Ok great. That's fixed with the latest problem. Sorry, one last thing now. The constructors for the classes have autoruns that use the arguments to the constructors. When the class is deserialized it's created with an empty constructor, meaning that the args are null which causes the autorun to fail. Any suggestions for ways to get around this?

**Comment by robclouth** [comment]
It's all in docs of course...need to define the factory.

**Comment by mweststrate** [comment]
yep, for future reference, see this section: https://github.com/mobxjs/serializr#6-use-custom-arguments-to-inject-stores-to-models

or assign a new function to `getDefaultModelSchema(clazz).factory = (context) => new X(context.args)`

**Comment by robclouth** [comment]
I had seen that section, I just didn't know what it meant until I needed it. Lazy some might say. Is there a way to use the decorator syntax with this? Would I just setup the class + decorators as usual and then underneath put getDefaultModelSchema(clazz).factory = (context) => new X(context.args)?

**Comment by mweststrate** [comment]
N.p. usually documentation doesn't make sense to me until I encounter the problem as well ;-). Yep that should be the way to go.

**Comment by robclouth** [comment]
Nailed it! P.s. thanks a bunch for putting the effort into mobx and serializr - coming from redux it's made by brain significantly more normal-shaped again.

**Comment by mweststrate** [comment]
:)
