### ISSUE TITLE
Mobx RootStore

### ISSUE THREAD

**Issue by samosaboy** [mobxjs/serializr#93]
How can I utilize the RootStore pattern of Mobx with Serializr and NextJS?

AFAIK, I am supposed to serialize the store server-side and deserialize on the client. I am kind of stuck as to how I can achieve that.

Here is what I've tried so far:

```
class RootStore {
     @serializable userStore
     @serializable authStore
 
     constructor() {
          this.userStore = new UserStore(this)
          this.authStore = new AuthStore(this)     
     }
}

createModelSchema(RootStore, {
	userStore: object(UserStore),
	authStore: object(AuthStore),
})

export const serializedStore = serialize(new RootStore())
export const deserializedStore = (serializedStore) => deserialize(RootStore, serializedStore)
```
Unfortunately, this fails.

**Comment by 1R053** [comment]
see this example for a nested class example. This should address the above use case, createModelSchema should not be required.

https://github.com/mobxjs/serializr/blob/f1d4259e6594565454d10a37fb5995dfae49314c/test/typescript/ts.ts#L258
