### ISSUE TITLE
Add feature to clear cache

### ISSUE THREAD

**Issue by DuYongLee** [mobxjs/serializr#95]
Currently, even if target-instance is destroyed, memory is not freed.
so i experimentally wrote the code  `rootContextCache.clear()`in deserialize function and then i checked memory was freed. 

I think that it need interface to clear cache or other method for managing memory.

maybe like this
`clearRootContextCache()` or `clearCache()`

what do you think about it?

if you agree about it, i will make PR.

or

if you have better idea, please let me know.

**Comment by 1R053** [comment]
Thanks, imo each object should handle its memory alloc / dealloc itself. So if it is an issue with the Context class, the dealloc should be solved there. Can you describe what you did to test this issue so I can reproduce it?

**Comment by 1R053** [comment]
After looking at the Context coding it seems, that the cache should be cleaned up automatically if the deserialization completes. However, in case of async logic that has not yet been resolved the cache entry remains until the resolution of the async elements. If they never resolve, you can call "cancelDeserialize".

**Comment by DuYongLee** [comment]
Thanks for your answer.

i'm using it for undo / redo algorithm so i'm making object snapshot with serialize and then restore snapshot with deserialize.

I'm making simple code as create-react-app for you (https://github.com/DuYongLee/test-serializr)

my test is simple.

1. make collection object(Messages) in App component constructor
2. click add btn to add Message to Messages
3. click serialize btn(like recording current object state) and then click deserialize btn(like restoring captured state)
4. capturing heap shanshot
5. repeat 3, 4

whenever repeating(5), Message object is increased in heap.

![snapshot2](https://user-images.githubusercontent.com/19799263/55931065-08c09c80-5c5f-11e9-9ef4-211784210b0d.png)

![snapshot3](https://user-images.githubusercontent.com/19799263/55931072-1118d780-5c5f-11e9-8372-c5212e346467.png)

![snapshot4](https://user-images.githubusercontent.com/19799263/55931080-17a74f00-5c5f-11e9-961b-260570e7cca0.png)

i hope it can help you to reproducing this event.

**Comment by svennergr** [comment]
I ran into the same issues as mentioned.
This can easily mitigated by using a WeakMap instead of a Map. #100

**Comment by DuYongLee** [comment]
@svennergr 
I tested your PR. 
It's work well. I hope your PR will soon be merged.
thanks!

**Comment by blacksteed232** [comment]
@1R053 Hi, could you take a look at the PR that @svennergr mentioned, I'm working on a moderately complex app that uses `serializr` and we do a lot of deserialization which will cause memory leak like this so our app will bloat up. Would be great if you could prioritize this. Thanks!

**Comment by mweststrate** [comment]
Solved in 1.5.2

**Comment by blacksteed232** [comment]
@mweststrate Thank you so so much!
