### ISSUE TITLE
Creating ModelSchema for abstract classes in TypeScript

### ISSUE THREAD

**Issue by Hamcker** [mobxjs/serializr#96]
Attempting to create `ModelSchema` via `createModelSchema` for abstract classes causes 

**Argument of type 'typeof Foo' is not assignable to parameter of type 'Clazz<Foo>'.
  Cannot assign an abstract constructor type to a non-abstract constructor type.**

the complete code is something like this:

`abstract class Foo {
    bar: string = 'bar'
}
const FooSchema = createModelSchema(Foo, {bar: primitive()});
`

**Comment by 1R053** [comment]
I guess this won't fix, as the class specified in a schema always needs to be instantiable in order to be deserializable.

**Comment by Hamcker** [comment]
Not always, but thanks to this library, I made a full-feautered serializer library for this.

**Comment by 1R053** [comment]
great, feel free to submit a PR here if it helps
